language: go
go:
  - 1.9.x
  - "1.10.x"
  - tip
go_import_path: code.avct.io/apexovernsq
script:
  - go vet ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
