[[constraint]]
  name = "github.com/apex/log"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/avct/apexovernsq"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.7"

[[constraint]]
  branch = "master"
  name = "github.com/tealeg/callstack"

[prune]
  go-tests = true
  unused-packages = true
